import * as XLSX from "xlsx";
import JSZip from "jszip";
import { ParsedSheet, ParsedSource, SourceKey } from "../types";
import { SOURCE_REGISTRY, SourceDefinition } from "./sourceRegistry";
function normalize(v: unknown) { return String(v ?? "").trim().toLowerCase().replace(/\s+/g, " "); }
function headerScore(headers: string[], requiredGroups: string[][]) { const set=new Set(headers.map(normalize)); let hits=0,total=0; for(const group of requiredGroups){total+=group.length;hits+=group.filter(h=>set.has(normalize(h))).length;} return total?hits/total:0; }
function detectSheet(data: unknown[][], def: SourceDefinition): ParsedSheet {
  let bestRow=0,bestScore=-1; const limit=Math.min(data.length,30);
  for(let i=0;i<limit;i++){const headers=(data[i]??[]).map(x=>String(x??"").trim());const score=headerScore(headers,def.requiredHeaders);if(score>bestScore){bestScore=score;bestRow=i;}}
  const rawHeaders=(data[bestRow]??[]).map((x,i)=>{const s=String(x??"").trim();return s||"Column "+(i+1);}); const headers:string[]=[]; const seen=new Map<string,number>();
  for(const h of rawHeaders){const n=seen.get(h)??0;seen.set(h,n+1);headers.push(n?h+"__"+(n+1):h);}
  const rows=data.slice(bestRow+1).map(row=>{const obj:Record<string,unknown>={};headers.forEach((h,i)=>obj[h]=row?.[i]??null);return obj;}).filter(r=>Object.values(r).some(v=>v!==null&&v!==""));
  const warnings:string[]=[]; if(bestScore<0.5)warnings.push("Header confidence is low ("+Math.round(bestScore*100)+"%)."); if(!rows.length)warnings.push("No data rows detected after the header row.");
  return {name:"",headers,rows,detectedHeaderRow:bestRow+1,warnings};
}
function matchDefinition(fileName:string,sheetNames:string[]):{def:SourceDefinition|null;confidence:number;reason:string}{let best={def:null as SourceDefinition|null,confidence:0,reason:"No matching source definition."};for(const def of SOURCE_REGISTRY){const fileHit=def.filenamePatterns.some(p=>p.test(fileName));const sheetHit=sheetNames.some(s=>def.sheetPatterns.some(p=>p.test(s)));const score=fileHit&&sheetHit?0.98:fileHit?0.82:sheetHit?0.55:0;if(score>best.confidence)best={def,confidence:score,reason:fileHit&&sheetHit?"Filename and sheet match.":fileHit?"Filename match.":"Sheet match."};}return best;}
export async function parseZip(file:File):Promise<{sources:ParsedSource[];warnings:string[]}>{const zip=await JSZip.loadAsync(file);const sources:ParsedSource[]=[];const warnings:string[]=[];const entries=Object.values(zip.files).filter(x=>!x.dir&&/\.(xlsx|xlsm|xls|csv)$/i.test(x.name)&&!/(^|\/)(~\$|\.|__macosx)/i.test(x.name));if(!entries.length)throw new Error("No supported Excel/CSV files were found in the ZIP.");for(const entry of entries){const bytes=await entry.async("uint8array");const fileName=entry.name.split("/").pop()||entry.name;const wb=XLSX.read(bytes,{type:"array",cellDates:true});const sheetData=wb.SheetNames.map(name=>({name,data:XLSX.utils.sheet_to_json(wb.Sheets[name],{header:1,raw:true}) as unknown[][]}));const match=matchDefinition(fileName,sheetData.map(x=>x.name));if(!match.def){warnings.push("Unrecognized file: "+fileName);continue;}const sheets:ParsedSheet[]=[];for(const sd of sheetData){const ps=detectSheet(sd.data,match.def);ps.name=sd.name;sheets.push(ps);}const sourceWarnings=sheets.flatMap(s=>s.warnings.map(w=>s.name+": "+w));sources.push({key:match.def.key as SourceKey,fileName,confidence:match.confidence,reason:match.reason,sheets,warnings:sourceWarnings});}const requiredMissing=SOURCE_REGISTRY.filter(d=>d.required&&!sources.some(s=>s.key===d.key)).map(d=>d.label);if(requiredMissing.length)warnings.push("Required sources missing: "+requiredMissing.join(", "));return {sources,warnings};}