import { SourceKey } from "../types";
export type SourceDefinition={key:SourceKey;label:string;required:boolean;filenamePatterns:RegExp[];sheetPatterns:RegExp[];requiredHeaders:string[][];description:string};
export const SOURCE_REGISTRY:SourceDefinition[]=[
{key:"inventory_ageing",label:"Inventory Ageing",required:false,filenamePatterns:[/inventory.*ageing/i,/ageing.*report/i],sheetPatterns:[/^dump$/i],requiredHeaders:[["SKU","Item Name","item.CF.Type of Item"],["Quantity","Value","Avg Rate"]],description:"Reference report containing detailed ageing buckets and asset values."},
{key:"inventory_valuation",label:"Inventory Valuation",required:false,filenamePatterns:[/inventory.*valuation/i,/valuation.*report/i],sheetPatterns:[/inventory valuation summary/i],requiredHeaders:[["Item ID","Item Name","Stock On Hand"],["Inventory Asset Value","sku","item.CF.Type of Item"]],description:"Reference report containing stock on hand, valuation, write-off and difference fields."},
{key:"assemblies",label:"Assemblies",required:false,filenamePatterns:[/assembl/i],sheetPatterns:[/bundles/i],requiredHeaders:[["Order Number","Bundled Quantity","Date"],["Composite SKU","Component SKU","Quantity Consumed"]],description:"Composite/bundle assembly transactions."},
{key:"bills",label:"Bills / Payables",required:true,filenamePatterns:[/^bill/i,/bill.*\(\d+\)/i],sheetPatterns:[/^bills$/i],requiredHeaders:[["Bill Date","Bill Number","Vendor Name"],["Due Date","Total","Bill Status"],["Purchase Order Number","SKU"]],description:"Vendor bills and payment status."},
{key:"composite_items",label:"Composite Items",required:false,filenamePatterns:[/composite[_ ]item/i],sheetPatterns:[/compositeitem/i],requiredHeaders:[["Composite Item Name","SKU","Mapped Item Name"],["Mapped Quantity","Mapped Item SKU"]],description:"Composite item definitions and component mappings."},
{key:"items",label:"Items",required:true,filenamePatterns:[/^item/i,/item.*\(\d+\)/i],sheetPatterns:[/^item$/i],requiredHeaders:[["Item Name","SKU","Item Type"]],description:"Item master."},
{key:"purchase_orders",label:"Purchase Orders",required:true,filenamePatterns:[/purchase[_ ]order/i],sheetPatterns:[/purchaseorder/i],requiredHeaders:[["Purchase Order Number","Purchase Order Date","Vendor Name"],["SKU","QuantityOrdered","QuantityReceived","QuantityBilled"]],description:"Purchase order line items and lifecycle quantities."},
{key:"purchase_receives",label:"Purchase Receipts",required:true,filenamePatterns:[/purchase[_ ]receive/i,/purchase.*receive/i],sheetPatterns:[/purchasereceive/i],requiredHeaders:[["Purchase Receive ID","Receive Number","Receive Date"],["PO Number","SKU","Quantity Received"]],description:"Physical receipts against purchase orders."},
{key:"transfers",label:"Transfer Orders",required:false,filenamePatterns:[/transfer[_ ]order/i,/transfer.*order/i],sheetPatterns:[/transfer order/i],requiredHeaders:[["Transfer Order#","Date","SKU"],["Quantity Transferred","From Location Name","To Location Name"]],description:"Inventory transfers between locations."},
{key:"vendors",label:"Vendors",required:true,filenamePatterns:[/vendor/i],sheetPatterns:[/^vendors$/i],requiredHeaders:[["Contact ID","Contact Name","Display Name"],["Notes","Status","GST Identification Number (GSTIN)"]],description:"Vendor master including OPS-VENDOR classification in Notes."},
{key:"b2b_sales_orders",label:"B2B Sales Orders",required:false,filenamePatterns:[/b2b.*sales/i,/sales.*order/i],sheetPatterns:[/sales/i,/b2b/i],requiredHeaders:[["Sales Order","Customer"],["Order Date","Quantity"]],description:"Optional B2B source; not present in the supplied sample ZIP."},
{key:"b2b_invoices",label:"B2B Invoices",required:false,filenamePatterns:[/b2b.*invoice/i,/invoice/i],sheetPatterns:[/invoice/i,/b2b/i],requiredHeaders:[["Invoice","Customer"],["Invoice Date","Total"]],description:"Optional B2B invoice source; not present in the supplied sample ZIP."}
];
export function getSource(key:SourceKey){return SOURCE_REGISTRY.find(x=>x.key===key)!;}